"""Parser unit tests for the four SWMM 5.2.4 water-quality rpt sections.

Ground truth: ``tests/fixtures/wq/wq_smoke.rpt`` — generated by the SWMM 5.2.4
engine from a 1-pollutant (TSS), 4-subcatchment model (PR1 smoke fixture).

Sections under test
-------------------
* Runoff Quality Continuity   (parse_variable_section)
* Quality Routing Continuity  (parse_variable_section)
* Subcatchment Washoff Summary (parse_variable_section)
* Link Pollutant Load Summary  (parse_variable_section)
* Outfall Loading Summary WQ extension (parse_section, min_columns=True)

Backward-compatibility lock
---------------------------
* parse_section on a non-WQ rpt returns the same 5-field rows as before
  (``pollutant_loads: {}``) — byte-identical to pre-WQ behaviour for callers
  that only read the 5 core fields.
"""
from __future__ import annotations

import unittest
from pathlib import Path

from agentic_swmm.agent.swmm_runtime.rpt_summary import (
    SECTIONS,
    parse_section,
    parse_variable_section,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
WQ_RPT = REPO_ROOT / "tests" / "fixtures" / "wq" / "wq_smoke.rpt"


@unittest.skipUnless(WQ_RPT.exists(), f"WQ fixture not found at {WQ_RPT}")
class RunoffQualityContinuityTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.rpt_text = WQ_RPT.read_text(encoding="utf-8")
        cls.rows = parse_variable_section(cls.rpt_text, SECTIONS["Runoff Quality Continuity"])

    def test_section_returns_rows(self) -> None:
        self.assertGreater(len(self.rows), 0, "Expected at least one row")

    def test_row_has_metric_and_values_keys(self) -> None:
        for row in self.rows:
            self.assertIn("metric", row)
            self.assertIn("values", row)

    def test_pollutant_tss_in_all_rows(self) -> None:
        for row in self.rows:
            self.assertIn("TSS", row["values"], f"TSS missing from row: {row}")

    def test_continuity_error_row_present(self) -> None:
        metrics = {r["metric"] for r in self.rows}
        self.assertIn("Continuity Error (%)", metrics)

    def test_continuity_error_value_is_float(self) -> None:
        for row in self.rows:
            if row["metric"] == "Continuity Error (%)":
                self.assertIsInstance(row["values"]["TSS"], float)

    def test_surface_runoff_row_positive(self) -> None:
        """Surface Runoff should be > 0 for a rainfall-driven run."""
        for row in self.rows:
            if row["metric"] == "Surface Runoff":
                self.assertGreater(row["values"]["TSS"], 0.0)
                return
        self.fail("'Surface Runoff' row not found in Runoff Quality Continuity")


@unittest.skipUnless(WQ_RPT.exists(), f"WQ fixture not found at {WQ_RPT}")
class QualityRoutingContinuityTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.rpt_text = WQ_RPT.read_text(encoding="utf-8")
        cls.rows = parse_variable_section(cls.rpt_text, SECTIONS["Quality Routing Continuity"])

    def test_section_returns_rows(self) -> None:
        self.assertGreater(len(self.rows), 0)

    def test_pollutant_tss_in_all_rows(self) -> None:
        for row in self.rows:
            self.assertIn("TSS", row["values"])

    def test_continuity_error_row_present(self) -> None:
        metrics = {r["metric"] for r in self.rows}
        self.assertIn("Continuity Error (%)", metrics)

    def test_continuity_error_value_is_float(self) -> None:
        for row in self.rows:
            if row["metric"] == "Continuity Error (%)":
                val = row["values"]["TSS"]
                self.assertIsInstance(val, float)
                # The smoke fixture has EMC washoff with no decay; routing
                # error is non-trivial (known from PR1 smoke: -38.789 %).
                self.assertAlmostEqual(val, -38.789, places=2)
                return
        self.fail("'Continuity Error (%)' not found in Quality Routing Continuity")

    def test_wet_weather_inflow_positive(self) -> None:
        for row in self.rows:
            if row["metric"] == "Wet Weather Inflow":
                self.assertGreater(row["values"]["TSS"], 0.0)
                return
        self.fail("'Wet Weather Inflow' row not found")

    def test_external_outflow_positive(self) -> None:
        for row in self.rows:
            if row["metric"] == "External Outflow":
                self.assertGreater(row["values"]["TSS"], 0.0)
                return
        self.fail("'External Outflow' row not found")


@unittest.skipUnless(WQ_RPT.exists(), f"WQ fixture not found at {WQ_RPT}")
class SubcatchmentWashoffSummaryTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.rpt_text = WQ_RPT.read_text(encoding="utf-8")
        cls.rows = parse_variable_section(cls.rpt_text, SECTIONS["Subcatchment Washoff Summary"])

    def test_returns_four_subcatchments(self) -> None:
        """Smoke fixture has 4 subcatchments: S1, S2, S3, S4."""
        names = [r["name"] for r in self.rows]
        self.assertEqual(sorted(names), ["S1", "S2", "S3", "S4"])

    def test_row_has_name_and_loads_keys(self) -> None:
        for row in self.rows:
            self.assertIn("name", row)
            self.assertIn("loads", row)

    def test_tss_load_is_positive_for_all_subcatchments(self) -> None:
        for row in self.rows:
            self.assertIn("TSS", row["loads"])
            self.assertGreater(row["loads"]["TSS"], 0.0)

    def test_tss_loads_match_fixture_values(self) -> None:
        """Pin exact values from the PR1 engine smoke output."""
        expected = {"S1": 0.109, "S2": 0.094, "S3": 0.112, "S4": 0.062}
        actual = {r["name"]: r["loads"]["TSS"] for r in self.rows}
        for sub, exp_val in expected.items():
            self.assertIn(sub, actual)
            self.assertAlmostEqual(actual[sub], exp_val, places=3,
                                   msg=f"{sub} TSS load: expected {exp_val}, got {actual[sub]}")

    def test_system_row_excluded(self) -> None:
        names = [r["name"] for r in self.rows]
        self.assertNotIn("System", names)


@unittest.skipUnless(WQ_RPT.exists(), f"WQ fixture not found at {WQ_RPT}")
class LinkPollutantLoadSummaryTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.rpt_text = WQ_RPT.read_text(encoding="utf-8")
        cls.rows = parse_variable_section(cls.rpt_text, SECTIONS["Link Pollutant Load Summary"])

    def test_returns_two_links(self) -> None:
        """Smoke fixture has 2 conduits: C1, C2."""
        names = [r["name"] for r in self.rows]
        self.assertEqual(sorted(names), ["C1", "C2"])

    def test_row_has_name_and_loads_keys(self) -> None:
        for row in self.rows:
            self.assertIn("name", row)
            self.assertIn("loads", row)

    def test_tss_loads_match_fixture_values(self) -> None:
        expected = {"C1": 0.295, "C2": 0.462}
        actual = {r["name"]: r["loads"]["TSS"] for r in self.rows}
        for link, exp_val in expected.items():
            self.assertAlmostEqual(actual[link], exp_val, places=3,
                                   msg=f"{link} TSS load: expected {exp_val}, got {actual[link]}")


@unittest.skipUnless(WQ_RPT.exists(), f"WQ fixture not found at {WQ_RPT}")
class OutfallLoadingWQExtensionTests(unittest.TestCase):
    """Regression test: Outfall Loading Summary gains TSS column when WQ active."""

    @classmethod
    def setUpClass(cls) -> None:
        cls.rpt_text = WQ_RPT.read_text(encoding="utf-8")
        cls.rows = parse_section(cls.rpt_text, SECTIONS["Outfall Loading Summary"])

    def test_returns_one_outfall(self) -> None:
        self.assertEqual(len(self.rows), 1)
        self.assertEqual(self.rows[0]["node"], "OF1")

    def test_core_hydraulic_fields_present(self) -> None:
        row = self.rows[0]
        for field in ("node", "flow_freq_pct", "avg_flow", "max_flow",
                      "total_volume_10_6_ltr", "pollutant_loads"):
            self.assertIn(field, row)

    def test_tss_load_in_pollutant_loads(self) -> None:
        row = self.rows[0]
        self.assertIn("TSS", row["pollutant_loads"])
        self.assertAlmostEqual(row["pollutant_loads"]["TSS"], 0.524, places=3)

    def test_non_wq_outfall_backward_compat(self) -> None:
        """Non-WQ rpt: pollutant_loads is always present but empty."""
        non_wq_rpt = """\
  ***********************
  Outfall Loading Summary
  ***********************

  -----------------------------------------------------------
                         Flow       Avg       Max       Total
                         Freq      Flow      Flow      Volume
  Outfall Node           Pcnt       CMS       CMS    10^6 ltr
  -----------------------------------------------------------
  O1                    52.35     0.205     3.366      46.402
  O2                    30.00     0.100     1.500      12.100
  -----------------------------------------------------------
  System                82.35     0.305     4.866      58.502
"""
        rows = parse_section(non_wq_rpt, SECTIONS["Outfall Loading Summary"])
        self.assertEqual(len(rows), 2)
        for row in rows:
            self.assertIn("pollutant_loads", row)
            self.assertEqual(row["pollutant_loads"], {})
        # Core fields byte-identical to pre-WQ behaviour.
        self.assertAlmostEqual(rows[0]["max_flow"], 3.366, places=3)
        self.assertAlmostEqual(rows[1]["max_flow"], 1.500, places=3)


class NonWQRptReturnsEmptyTests(unittest.TestCase):
    """parse_variable_section returns [] for sections absent in a non-WQ rpt."""

    _NON_WQ_RPT = """\
  EPA STORM WATER MANAGEMENT MODEL - VERSION 5.2 (Build 5.2.4)

  **************************        Volume         Depth
  Runoff Quantity Continuity     hectare-m            mm
  **************************     ---------       -------
  Total Precipitation ......         0.092        26.208
  Continuity Error (%) .....        -0.171
"""

    def test_runoff_quality_continuity_absent(self) -> None:
        rows = parse_variable_section(self._NON_WQ_RPT, SECTIONS["Runoff Quality Continuity"])
        self.assertEqual(rows, [])

    def test_quality_routing_continuity_absent(self) -> None:
        rows = parse_variable_section(self._NON_WQ_RPT, SECTIONS["Quality Routing Continuity"])
        self.assertEqual(rows, [])

    def test_subcatchment_washoff_absent(self) -> None:
        rows = parse_variable_section(self._NON_WQ_RPT, SECTIONS["Subcatchment Washoff Summary"])
        self.assertEqual(rows, [])

    def test_link_pollutant_load_absent(self) -> None:
        rows = parse_variable_section(self._NON_WQ_RPT, SECTIONS["Link Pollutant Load Summary"])
        self.assertEqual(rows, [])


if __name__ == "__main__":
    unittest.main()
